### PR TITLE
working on the courses files

### PR DESCRIPTION
**Pull request by judieshivan**
# Description

this pull request is aimed at reviewing the changes made in the create-course, add-course and manage-course files. please give in your feedbacks.
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Can This Been Tested?

one can review the code, run it and the approve it for merging.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Josh03-spec — APPROVED** [review]
Your code is clean and  readable, nice job.

**Comment by mosesmulumba** [comment]
@Josh03-spec  I am not sure you checkout the branch and run it locally. The code is clean but it has some unnecessarily things that the database is not even going to take in. So please reveiw the code very well.

**Comment by mosesmulumba** [comment]
@judieshivan look at what the srms_version_1.sql file expects to get, then the forms are aslo expected to capture that data that is only going to be entered. The created_date column and updation_date are not entered by the user. please work on removing them from the form and also make sure you can checkout the code you have written before you push.

**Review by mosesmulumba — CHANGES_REQUESTED** [review]
Please work on the areas i have mentioned.

**Pull request merged**
